version: '3'
services:
  node-app:
    build: .
    ports:
      - "4000:9000"
    env_file:
      - ./.env



  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:  
